### ISSUE TITLE
allow to make message "sent"

### ISSUE THREAD

**Issue by ralfhauser** [ctabin/jotlmsg#11]
in writeTo()

you have the line

   topLevelChunk.setProperty(new PropertyValue(MAPIProperty.MESSAGE_FLAGS, FLAG_READABLE | FLAG_WRITEABLE, ByteBuffer.allocate(4).putInt(8).array())); //unsent message
        

how that need to be changed to show the message as sent ?

**Comment by ctabin** [comment]
Fixed in #13 with the new methods `getSentDate()` and `setSendDate()`
