### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign

### ISSUE THREAD

**Issue by sep1** [ctabin/jotlmsg#28]
Hello, i'm getting this error trying to do run as -> maven install.

Can someone please help me?

**Comment by sep1** [comment]
ok, i've solved this error. Now i'm getting this:
`Project build error: Invalid packaging for parent POM ch.astorm:jotlmsg:1.4, must be "pom" but is "jar"`

**Comment by ctabin** [comment]
Hello,

It has probably something to do with your pom configuration, but I can't help you on that.
As written in the documentation, the dependency should be:
```xml
<dependency>
    <groupId>ch.astorm</groupId>
    <artifactId>jotlmsg</artifactId>
    <version>1.4</version>
</dependency>
```

Best,
Cédric
