### ISSUE TITLE
Edit text body with HTML tag on the generated .msg file

### ISSUE THREAD

**Issue by sep1** [ctabin/jotlmsg#29]
Hello, once created all the emails i need to send i cant manually set the HTML tags (add bold text, add italic text, ecc) on the outlook generated .msg file directly on the outlook program. Is there a solution to this? Cause i need to manually add some tags first to send them. If not, is there a method to generate the emails with the HTML tags? Like bold text, italic text ecc.?

P.S. thanks for this API project. It's really usefull to me.

**Comment by ctabin** [comment]
Hi,

Unfortunately no. I wrote the comment below in the `setPlainText` method:
```
Defines the plain text body of the message. Currently, there is no way to define
a formatted message (HTML/RTF) for technical reasons (RTF compression and
{@code PidTagBodyHtml} not supported by Outlook).
```
I did already spent some time to try to make Outlook understand HTML without success...
Maybe I should probably mention this in the lmitations.

Best,
Cédric
