### ISSUE TITLE
Body is another attachment when you send the msg

### ISSUE THREAD

**Issue by chapus** [ctabin/jotlmsg#55]
First I create the msg file and save it to filesystem, after that, I use the msg file and:
`MimeMessage email= message.toMimeMessage();`  with that I send the message.

But when i check the email the body is an attachment, is possible to sent it like any other email ?

![image](https://user-images.githubusercontent.com/1543053/96896993-cc751b80-1453-11eb-9ae6-600a0889dd58.png)

**Comment by ctabin** [comment]
Hi @chapus and thanks for your report.
Can you please provide a simple test case ? Thanks !

**Comment by chapus** [comment]
`OutlookMessage message = new OutlookMessage();`

`String body = "Text line 1 \n\n";`
`body = body + "More text in another line \n";`

`message.setSubject("Test subject");`
`message.setPlainTextBody(body);`

`InputStream isPdf = ...`
`InputStream isXml= ...`
`message.addAttachment("test.pdf", "application/pdf", isPdf);`
`message.addAttachment("test.xml", "text/xml", isXml);`

`File fileMsg = new File("path/test.msg");`
`message.writeTo(fileMsg);`

Then I send the message in another process:

`MimeMessage test = message.toMimeMessage();`
`emailSender.send(test);`

**Comment by ctabin** [comment]
@chapus Thanks ! Could you try my modification in #56 and tell me if this does the trick ?

**Comment by chapus** [comment]
Great, now is working as expected. Thank you!.
